CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  display_name VARCHAR(100),
  password_hash VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  clock_in TIMESTAMP,
  clock_out TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_att_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT uq_att UNIQUE (user_id, work_date)
);
CREATE TABLE IF NOT EXISTS application_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(30) NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  start_date DATE,
  end_date DATE,
  target_date DATE,
  overtime_minutes INT,
  requested_shift VARCHAR(100),
  reason VARCHAR(500),
  decided_by_id BIGINT,
  decision_note VARCHAR(500),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  decided_at TIMESTAMP,
  CONSTRAINT fk_req_requester FOREIGN KEY (requester_id) REFERENCES users(id),
  CONSTRAINT fk_req_decider FOREIGN KEY (decided_by_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_req_status ON application_requests(status);
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id BIGINT NOT NULL,
  receiver_id BIGINT NOT NULL,
  body VARCHAR(2000) NOT NULL,
  sent_at TIMESTAMP NOT NULL,
  read_at TIMESTAMP,
  CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES users(id),
  CONSTRAINT fk_msg_receiver FOREIGN KEY (receiver_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_msg_receiver ON messages(receiver_id, sent_at);
CREATE TABLE IF NOT EXISTS mental_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  check_date DATE NOT NULL,
  score INT NOT NULL,
  comment VARCHAR(1000),
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_mental_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT uq_mental UNIQUE (user_id, check_date)
);
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id BIGINT,
  actor_username VARCHAR(50),
  actor_role VARCHAR(20),
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100),
  entity_id VARCHAR(100),
  detail VARCHAR(2000),
  ip_address VARCHAR(45),
  created_at TIMESTAMP NOT NULL,
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at);
CREATE TABLE IF NOT EXISTS password_reset_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id BIGINT NOT NULL,
  requested_by_id BIGINT,
  status VARCHAR(20) NOT NULL,
  requested_at TIMESTAMP NOT NULL,
  requested_ip VARCHAR(64),
  decided_by_id BIGINT,
  decided_at TIMESTAMP,
  decided_ip VARCHAR(64),
  decision_note VARCHAR(1000),
  CONSTRAINT fk_prr_target FOREIGN KEY (target_user_id) REFERENCES users(id),
  CONSTRAINT fk_prr_requester FOREIGN KEY (requested_by_id) REFERENCES users(id),
  CONSTRAINT fk_prr_decider FOREIGN KEY (decided_by_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_prr_status ON password_reset_request(status, requested_at);
INSERT INTO users (username, display_name, password_hash, role, enabled, created_at, updated_at)
SELECT
  '1',
  STRINGDECODE('\u7BA1\u7406\u8005'),
  '$2a$10$QwnBiblyStk1UdX56vTKtuicojAjp9sORk.NB7/g5Oi8Fdn.qY3ey',
  'ADMIN',
  TRUE,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = '1');